In [14]:
import numpy as np
import matplotlib.pyplot as plt

#url
#https://tjo.hatenablog.com/entry/2013/05/01/190247


In [18]:
# 識別関数の本体：y=w'xを計算してるだけ
def predict(wvec,xvec):
    out=np.dot(wvec,xvec)
    if out>=0:
        res=1
    else:
        res=-1
    return [res,out]

# 学習部：識別関数に学習データを順繰りに入れて、
# 重みベクトルを更新する
def train(wvec,xvec,label):
    [res,out]=predict(wvec,xvec)
    c=0.5 # 学習係数。大き過ぎてもまともに学習してくれないので1未満ぐらいで
    if out*label<0:
        wtmp=wvec+c*label*xvec
        return wtmp
    else:
        return wvec

In [52]:
# 学習データは100個
item_num=100 
# 収束判定は一切してないけどとりあえず1000回ループ
loop=1000   
init_wvec=[1,-1,1] # 重みベクトルの初期値、適当

In [53]:
# 学習データはxy平面の第1象限と第3象限に50個ずつ
 # np.random.randomでばらつかせてみた
x1_1=np.ones(int(item_num/2))+10*np.random.random(int(item_num/2))
x1_2=np.ones(int(item_num/2))+10*np.random.random(int(item_num/2))
x2_1=-np.ones(int(item_num/2))-10*np.random.random(int(item_num/2))
x2_2=-np.ones(int(item_num/2))-10*np.random.random(int(item_num/2))
# こいつはバイアス項、今回は無視して1に固定
z=np.ones(int(item_num/2)) 

In [54]:
 # 学習データを1つのマトリクスにまとめる
# 第1象限
x1=np.c_[x1_1,x1_2,z]
# 第３象限
x2=np.c_[x2_1,x2_2,z]
class_x=np.array(np.r_[x1,x2])

In [55]:
# NumPy.ndarrayはappend()メソッドが使えないので
# 糞コードらしく初期arrayを作ってそこに垂直に足していく策を取る
wvec=np.vstack((init_wvec,init_wvec))

In [59]:
# ループ回数の分だけ繰り返しつつ、重みベクトルを学習させる
for j in range(loop):
    for i in range(item_num):
        wvec_new=train(wvec[-1],class_x[i,:],label_x[i])
        print(wvec_new)

[ 2.99825192  4.27827123  1.5       ]
[ 1 -1  1]
[ 1.81870471  3.38621822  1.5       ]
[ 2.89597668  2.16472119  1.5       ]
[ 3.07266443  3.00083125  1.5       ]
[ 1 -1  1]
[ 1 -1  1]
[ 1 -1  1]
[ 1 -1  1]
[ 2.6576777   2.29640661  1.5       ]
[ 2.05784223  1.86033357  1.5       ]
[ 1 -1  1]
[ 5.50573136  4.38358269  1.5       ]
[ 3.02423366  2.88304606  1.5       ]
[ 1 -1  1]
[ 3.0491263  2.6720338  1.5      ]
[ 1 -1  1]
[ 1 -1  1]
[ 2.83719386  3.20627522  1.5       ]
[ 1 -1  1]
[ 1 -1  1]
[ 4.40777219  4.11069341  1.5       ]
[ 1.70998337  2.54656464  1.5       ]
[ 1 -1  1]
[ 4.21991404  3.73973659  1.5       ]
[ 2.85947172  3.8553205   1.5       ]
[ 1 -1  1]
[ 1 -1  1]
[ 2.31164636  1.01660737  1.5       ]
[ 1 -1  1]
[ 2.25813057  3.67039924  1.5       ]
[ 1 -1  1]
[ 1 -1  1]
[ 1 -1  1]
[ 1 -1  1]
[ 1 -1  1]
[ 1.50471385  1.18151324  1.5       ]
[ 3.57317428  4.31596096  1.5       ]
[ 1 -1  1]
[ 3.81394276  2.56649764  1.5       ]
[ 1 -1  1]
[ 1 -1  1]
[ 3.22810335  2.82219641  1.